### ISSUE TITLE
PDOException/InvalidQueryException on export

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-BulkExport#4]
With each exporter (from BulkExport-3.3.12.18 + Log-3.3.12.8), after the export definition JSON is shown and I press "Start Export", I get a "Omeka S encountered an error" message.

The PHP errorlog shows the following:

```
[28-Jul-2021 15:51:49 UTC] PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"log" ("created","severity","message","owner_id","context") VALUES ('2021-07-...' at line 1 in /****/omeka-s/vendor/laminas/laminas-db/src/Adapter/Driver/Pdo/Statement.php:238
Stack trace:
#0 /****/omeka-s/vendor/laminas/laminas-db/src/Adapter/Driver/Pdo/Statement.php(238): PDOStatement->execute()
#1 /****/omeka-s/vendor/laminas/laminas-log/src/Writer/Db.php(128): Laminas\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /****/omeka-s/vendor/laminas/laminas-log/src/Writer/AbstractWriter.php(282): Laminas\Log\Writer\Db->doWrite()
#3 /****/omeka-s/vendor/laminas/laminas-log/src/Logger.php(459): Laminas\Log\Writer\AbstractWriter->write()
#4 /****/omeka-s/vendor/laminas/laminas-log/src/Logger.php(502): Laminas\Log\Logger->log()
#5 /****/omeka-s/application/src/Mvc/ExceptionListener.php(54): Laminas\Log\Logger->err()
#6 /****/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Omeka\Mvc\ExceptionListener->handleException()
#7 /****/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners()
#8 /****/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(153): Laminas\EventManager\EventManager->triggerEvent()
#9 /****/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#10 /****/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#11 /****/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#12 /****/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#13 {main}

Next Laminas\Db\Adapter\Exception\InvalidQueryException: Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"log" ("created","severity","message","owner_id","context") VALUES ('2021-07-...' at line 1) in /****/omeka-s/vendor/laminas/laminas-db/src/Adapter/Driver/Pdo/Statement.php:243
Stack trace:
#0 /****/omeka-s/vendor/laminas/laminas-log/src/Writer/Db.php(128): Laminas\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /****/omeka-s/vendor/laminas/laminas-log/src/Writer/AbstractWriter.php(282): Laminas\Log\Writer\Db->doWrite()
#2 /****/omeka-s/vendor/laminas/laminas-log/src/Logger.php(459): Laminas\Log\Writer\AbstractWriter->write()
#3 /****/omeka-s/vendor/laminas/laminas-log/src/Logger.php(502): Laminas\Log\Logger->log()
#4 /****/omeka-s/application/src/Mvc/ExceptionListener.php(54): Laminas\Log\Logger->err()
#5 /****/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Omeka\Mvc\ExceptionListener->handleException()
#6 /****/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners()
#7 /****/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(153): Laminas\EventManager\EventManager->triggerEvent()
#8 /****/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#9 /****/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#10 /****/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#11 /****/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#12 {main}
```
(nothing in application.log and sql.log)

**Comment by Daniel-KM** [comment]
Thanks for the report. Do you have the last version of module Log (3.3.12.8)?

**Comment by coret** [comment]
@Daniel-KM yes, as stated in issue.

**Comment by coret** [comment]
So the error shows the code trying to insert values in the "log" table for fields "created","severity","message","owner_id" and "context". When I look at the table definition of "log" is see "reference" is a required field too.

**Comment by Daniel-KM** [comment]
Normally, this is fixed in last version of Log.

**Comment by hxsllc** [comment]
I received the same issue. Working on a site migration today. I'm running all core and module upgrades, will report back.

**Comment by hxsllc** [comment]
I am able to export with Omeka-S v3.1.1, Log version 3.3.12.13 and Bulk Export version 3.3.12.19.

I was unable to install Bulk Export version 3.3.13.0 and 3.3.13.1 on metascripta.org, there was an error upon Install. But I did not receive the same install error on the migration target server with a fresh Omeka-S install. So will not file a separate issue about that until I figure it out.

**Comment by hxsllc** [comment]
Actually, scratch that - I did not encounter the same issue as reported above (which I previously encountered). But upon running a TSV export, the logs show this error:

Fatal error: Uncaught Error: Call to a member function fopen() on null in /var/www/html/modules/CSVImport/vendor/box/spout/src/Spout/Writer/AbstractWriter.php:114
Stack trace:
#0 /var/www/html/modules/BulkExport/src/Writer/AbstractSpreadshe

**Comment by hxsllc** [comment]
There is a stray "," in 3.3.13.0 and 3.3.13.1 (perhaps this is only an issue with PHP7.2 and not PHP7.4?).

ParseError syntax error, unexpected ')'
Details:
ParseError: syntax error, unexpected ')' in /var/www/html/modules/BulkExport/Module.php:66

Upon updating to Bulk Export 3.3.13.1 and manually fixing the issue, I was able to install successfully but now get the following error:
The dependency Box/Spout version should be >= 3.0. Upgrade dependencies or CSV Import. See readme.

**Comment by Daniel-KM** [comment]
Fixed.
