### ISSUE TITLE
Laminas\Uri\Exception\InvalidUriException: URI is not valid and cannot be converted into a string

### ISSUE THREAD

**Issue by hxsllc** [Daniel-KM/Omeka-S-module-BulkExport#7]
This error is encountered with the latest version of Omeka-S and Bulk Export. CSV Import was uninstalled to get past the 
Box/Spout issue.

Strange because there are no URI values in the site data.

Laminas\Uri\Exception\InvalidUriException: URI is not valid and cannot be converted into a string in /var/www/html/vendor/laminas/laminas-uri/src/Uri.php:363
Stack trace:
#0 /var/www/html/vendor/laminas/laminas-router/src/Http/TreeRouteStack.php(425): Laminas\Uri\Uri->toString()
#1 /var/www/html/modules/CleanUrl/src/View/Helper/CleanUrl.php(100): Laminas\Router\Http\TreeRouteStack->assemble(Array, Array)
#2 /var/www/html/application/src/Api/Representation/ItemRepresentation.php(100): CleanUrl\View\Helper\CleanUrl->__invoke('site/resource-i...', Array, Array)
#3 /var/www/html/modules/BulkExport/src/Traits/MetadataToStringTrait.php(52): Omeka\Api\Representation\ItemRepresentation->siteUrl('web', true)
#4 /var/www/html/modules/BulkExport/src/Writer/AbstractSpreadsheetWriter.php(104): BulkExport\Writer\AbstractFieldsWriter->stringMetadata(Object(Omeka\Api\Representation\ItemRepresentation), 'url')
#5 /var/www/html/modules/BulkExport/src/Writer/AbstractFieldsWriter.php(287): BulkExport\Writer\AbstractSpreadsheetWriter->getDataResource(Object(Omeka\Api\Representation\ItemRepresentation))
#6 /var/www/html/modules/BulkExport/src/Writer/AbstractFieldsWriter.php(215): BulkExport\Writer\AbstractFieldsWriter->appendResourcesForResourceType('o:Item')
#7 /var/www/html/modules/BulkExport/src/Writer/AbstractFieldsWriter.php(150): BulkExport\Writer\AbstractFieldsWriter->appendResources()
#8 /var/www/html/modules/BulkExport/src/Job/Export.php(67): BulkExport\Writer\AbstractFieldsWriter->process()
#9 /var/www/html/application/src/Job/DispatchStrategy/Synchronous.php(34): BulkExport\Job\Export->perform()
#10 /var/www/html/modules/Log/src/Job/Dispatcher.php(32): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#11 /var/www/html/application/data/scripts/perform-job.php(66): Log\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Log\Job\DispatchStrategy\Synchronous))
#12 {main}

**Comment by hxsllc** [comment]
This is a conflict with Clean URL.
