### ISSUE TITLE
Vague error message when the permissions are wrong in the export files dir

### ISSUE THREAD

**Issue by OyvindLGjesdal** [Daniel-KM/Omeka-S-module-BulkExport#9]
I got this error:

```
Error
Call to a member function err() on null

Details:

Error: Call to a member function err() on null in /media/omeka-s/modules/BulkExport/src/Writer/AbstractWriter.php:173
Stack trace:
#0 /media/omeka-s/modules/BulkExport/src/Writer/AbstractFieldsWriter.php(101): BulkExport\Writer\AbstractWriter->checkDestinationDir()
#1 /media/omeka-s/modules/BulkExport/src/Writer/OpenDocumentTextWriter.php(29): BulkExport\Writer\AbstractFieldsWriter->isValid()
#2 /media/omeka-s/modules/BulkExport/src/Controller/Admin/ExporterController.php(242): BulkExport\Writer\OpenDocumentTextWriter->isValid()
#3 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): BulkExport\Controller\Admin\ExporterController->startAction()
#4 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#5 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#6 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#7 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#8 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#9 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#10 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#11 /var/www/html/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#12 {main}
```

when I exported while the php user didn't have permissions on the directory. The error disappears when I fixed the permissions, so it is a minor issue to me, but I think another more human readable error message was supposed to appear after I looked at the stacktraces.

I would expect the message from *BulkExport/src/Writer/AbstractFieldsWriter.php* to be shown
```
                'Output directory "{folder}" is not writeable.', // @translate
```

**Comment by Daniel-KM** [comment]
Fixed.
